title: Aratrik Chattopadhyay - Portfolio
email: aratrik@example.com
description: >- 
  Portfolio of Aratrik Chattopadhyay — Senior Tech Lead at Mercedes-Benz R&D
baseurl: "" 
url: "https://your-username.github.io" 
theme: jekyll-theme-dark-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
