title: Aratrik Chattopadhyay - Portfolio
email: aratrik@example.com
description: >- 
  Portfolio of Aratrik Chattopadhyay — Senior Tech Lead at Mercedes-Benz R&D
baseurl: "" 
url: "https://aratrik.github.io/Aratrik_website/" 
theme: jekyll-theme-dark-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
